### ISSUE TITLE
Cloud Errors

### ISSUE THREAD

**Issue by take-a-CHANCE** [mumblepins/bluz-gateway#15]
`Bluz f*******bc: cloud error: { [Error: getaddrinfo ENOTFOUND device.spark.io device.spark.io:5683]
code: 'ENOTFOUND',
errno: 'ENOTFOUND',
syscall: 'getaddrinfo',
hostname: 'device.spark.io',
host: 'device.spark.io',
port: 5683 }
`

Get this when trying to connect to my bluz, Fresh install without init.d as that doesn't seem to work

**Comment by mumblepins** [comment]
Server was probably down, reopen if this is still happening, as this should only depend on the system ip address lookup

**Comment by hgoldwire** [comment]
Seeing the same thing since yesterday:

Bluz f*********6c: cloud error: { Error: getaddrinfo ENOTFOUND device.spark.io device.spark.io:5683
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'device.spark.io',
  host: 'device.spark.io',
  port: 5683 }
